# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('domain', models.TextField(max_length=256, unique=True)),
                ('key', models.TextField(max_length=256)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Extended', 'Extended'), ('Finished', 'Finished'), ('Closed', 'Closed'), ('Removed', 'Removed')], default='Acitve', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Auction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.TextField(max_length=16)),
                ('description', models.TextField(max_length=256)),
                ('unit', models.TextField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=16)),
                ('dimensions', models.TextField(max_length=16)),
                ('unit', models.TextField(max_length=16)),
                ('price', models.FloatField()),
                ('prints', models.IntegerField()),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Application')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=16)),
                ('restriction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Restriction')),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Space')),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.SpaceCategory'),
        ),
        migrations.AddField(
            model_name='space',
            name='restrictions',
            field=models.ManyToManyField(through='ads.SpaceRestriction', to='ads.Restriction'),
        ),
        migrations.AddField(
            model_name='auction',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Space'),
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.ApplicationCategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
