# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
