# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20171126_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='price',
            new_name='price_usd',
        ),
        migrations.RemoveField(
            model_name='restriction',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='space',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='space',
            name='unit',
        ),
    ]
