# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20171126_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='x_size',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='y_size',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
