# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20171126_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='country',
            field=models.TextField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
