# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_ip_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=16)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ads.Space')),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_restrictions', to='ads.Restriction')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='data_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.TextField(default='Badds', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_restrictions', to='ads.Restriction'),
        ),
    ]
