# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_auto_20171127_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='restrictions',
            field=models.ManyToManyField(related_name='ResourceRestrictions', through='ads.ResourceRestriction', to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='space',
            name='restrictions',
            field=models.ManyToManyField(related_name='SpaceRestrictions', through='ads.SpaceRestriction', to='ads.Restriction'),
        ),
    ]
