# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_auto_20171127_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.TextField(),
        ),
    ]
