# Generated by Django 2.0.2 on 2018-05-23 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_auto_20171127_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.AdvertisementCategory'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.ApplicationCategory'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='ads.Space'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.AuctionStatus'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biddings', to='ads.Auction'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.Advertisement'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.Space'),
        ),
        migrations.AlterField(
            model_name='contractiplog',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ips', to='ads.Contract'),
        ),
        migrations.AlterField(
            model_name='contractiplog',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.Ip'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='ads.Advertisement'),
        ),
        migrations.AlterField(
            model_name='resourcerestriction',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='ads.Resource'),
        ),
        migrations.AlterField(
            model_name='resourcerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_restrictions', to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='space',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='ads.Application'),
        ),
        migrations.AlterField(
            model_name='space',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.AdvertisementCategory'),
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='space_restrictions', to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='ads.Space'),
        ),
    ]
