# Generated by Django 2.0.2 on 2018-06-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_auto_20180523_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcategory',
            options={'verbose_name_plural': 'Advertisement Categories'},
        ),
        migrations.AlterModelOptions(
            name='auctionstatus',
            options={'verbose_name_plural': 'Auction Statuses'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='advertisement_category',
        ),
        migrations.RemoveField(
            model_name='space',
            name='category',
        ),
        migrations.DeleteModel(
            name='AdvertisementCategory',
        ),
    ]
