# Generated by Django 2.0.2 on 2018-06-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_auto_20180612_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='ads.Advertisement'),
        ),
    ]
