# Generated by Django 2.0.2 on 2018-06-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_auto_20180623_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url_link',
            field=models.TextField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionstatus',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Extended', 'Extended'), ('Closed', 'Closed'), ('Removed', 'Removed')], default='Acitve', max_length=16),
        ),
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.TextField(max_length=128),
        ),
    ]
