# Generated by Django 2.2.2 on 2019-11-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_auto_20191127_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
