# Generated by Django 2.2.2 on 2019-11-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
