# Generated by Django 2.2.2 on 2019-11-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_contract_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_date',
        ),
        migrations.AddField(
            model_name='auction',
            name='contract_duration_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
