# Generated by Django 2.2.4 on 2019-11-29 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_auto_20191129_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
