# Generated by Django 2.2.4 on 2019-12-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0030_auction_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='prints',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidding',
            name='advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='biddings', to='ads.Advertisement'),
            preserve_default=False,
        ),
    ]
