# Generated by Django 2.2.4 on 2019-12-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_auto_20191201_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractiplog',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contractiplog',
            name='gender',
            field=models.TextField(max_length=1, null=True),
        ),
    ]
