# Generated by Django 2.2.4 on 2019-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_auto_20191204_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AuctionStatus',
        ),
    ]
