# Generated by Django 2.2.4 on 2019-12-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_auto_20191205_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.Restriction'),
        ),
    ]
