# Generated by Django 2.2.8 on 2019-12-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_creditslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditsLog',
        ),
    ]
