# Generated by Django 2.2.8 on 2019-12-16 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0036_delete_creditslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='text',
            field=models.TextField(default='Example text.', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcerestriction',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ads.Resource'),
        ),
        migrations.AlterField(
            model_name='resourcerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_restrictions', to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='ads.Space'),
        ),
    ]
