version: "3.7"

services:
    postgres:
        image: postgres:alpine
        env_file:
          - ./.env
        restart: always
        volumes:
          - db_data:/var/lib/postgresql/data
    web:
        build: web/
        restart: always
        env_file:
          - ./.env
        depends_on:
          - "db"
        volumes:
          - web_static:/usr/src/web/static
          - web_uwsgi:/usr/src/web/uwsgi
          - panel_build:/usr/src/web/static/panel
    panel:
        build: web_panel/
        volumes:
          - ./web_panel/build:/usr/src/panel/build
          - ./web_panel/node_modules:/usr/src/panel/node_modules
          - ./web_panel/package-lock.json:/usr/src/panel/package-lock.json
          - ./web_panel/src:/usr/src/panel/src:rw
    nginx:
        image: nginx:alpine
        restart: always
        ports:
          - "80:80"
        depends_on:
          - "web"
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
          - panel_build:/usr/src/web/static/panel
          - web_static:/usr/src/web/static
          - web_uwsgi:/usr/src/web/uwsgi

volumes:
  db_data:
  web_static:
  web_uwsgi:
  panel_build:
