version: "3.7"

services:
    postgres:
        image: postgres:12-alpine
        env_file:
          - ./.env
        restart: always
        volumes:
          - db_data:/var/lib/postgresql/data
    web:
        build: web/
        restart: always
        env_file:
          - ./.env
        depends_on:
          - postgres
        ports:
          - "8080:8080"
        volumes:
          - ./web_panel/build:/usr/src/web/static/panel
          - ./web/templates:/usr/src/web/templates
          - ./web/landing:/usr/src/web/landing
          - ./web/badds:/usr/src/web/badds
          - ./web/ads:/usr/src/web/ads
    panel:
        build: web_panel/
        volumes:
          - ./web_panel/build:/usr/src/panel/build
          - ./web_panel/node_modules:/usr/src/panel/node_modules
          - ./web_panel/package-lock.json:/usr/src/panel/package-lock.json
          - ./web_panel/src:/usr/src/panel/src:rw
          - ./web_panel/public:/usr/src/panel/src/public:rw

volumes:
  db_data:
  panel_build:
