version: "3.7"

services:
    badds:
        image: localhost:5000/gema/badds
        labels:
          gema.service: badds
          gema.auth: 1
          gema.port: 8080
          gema.subdomain: badds
        env_file:
          - ./.env
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
          placement:
            constraints: [node.labels.category == main]
        networks:
          - gema
        volumes:
          - ./web_panel/build:/usr/src/web/static/panel
          - ./web/templates:/usr/src/web/templates
          - ./web/landing:/usr/src/web/landing
          - ./web/badds:/usr/src/web/badds
          - ./web/ads:/usr/src/web/ads
    badds_panel:
        image: localhost:5000/gema/badds-panel
        deploy:
          mode: replicated
          replicas: 1
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
          placement:
            constraints: [node.labels.category == main]
        networks:
          - gema
        volumes:
          - ./web_panel/build:/usr/src/panel/build
          - ./web_panel/node_modules:/usr/src/panel/node_modules
          - ./web_panel/package-lock.json:/usr/src/panel/package-lock.json
          - ./web_panel/src:/usr/src/panel/src:rw
          - ./web_panel/public:/usr/src/panel/src/public:rw

networks:
  gema:
    external: true
