# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_profile_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='credit',
            new_name='credits',
        ),
    ]
