# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20171126_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='advertisment',
        ),
        migrations.AddField(
            model_name='resource',
            name='advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ads.Advertisement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.AdvertisementCategory'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ApplicationCategory'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='ads.Space'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.AuctionStatus'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddings', to='ads.Auction'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.AdvertisementCategory'),
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='ads.Space'),
        ),
    ]
