# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20171126_0822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractIpRegistry',
            new_name='ContractIpLog',
        ),
    ]
