# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20171127_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_restrictions', to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='spacerestriction',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_restrictions', to='ads.Restriction'),
        ),
    ]
