# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_auto_20171127_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='restrictions',
            field=models.ManyToManyField(through='ads.ResourceRestriction', to='ads.Restriction'),
        ),
        migrations.AlterField(
            model_name='resourcerestriction',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ads.Resource'),
        ),
    ]
