# Generated by Django 2.2.2 on 2019-06-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20171128_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_purchase_amount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_purchase_id',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_purchase_link',
            field=models.TextField(default=None, null=True),
        ),
    ]
